### ISSUE TITLE
Does this work with NNG2?

### ISSUE THREAD

**Issue by IvRRimum** [burkeholland/nativscript-statusbar#4]
```
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
JS:     at resolvePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:393:13
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:28)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:6242:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:34)
JS:     at Zone.run (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:43)
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:57
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:6233:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS: Unhandled Promise rejection: this.page.frame._getNavBarVisible is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: this.page.frame._getNavBarVisible is not a function 
TypeError: this.page.frame._getNavBarVisible is not a function
JS:     at ActionBar.update (/data/data/org.nativescript.test/files/app/tns_modules/ui/action-bar/action-bar.js:146:50)
JS:     at ActionBar.onLoaded (/data/data/org.nativescript.test/files/app/tns_modules/ui/action-bar/action-bar.js:140:14)
JS:     at eachChild (/data/data/org.nativescript.test/files/app/tns_modules/ui/core/view-common.js:736:23)
JS:     at Page._eachChildView (/data/data/org.nativescript.test/files/app/tns_modules/ui/page/page-common.js:286:9)
JS:     at Page.View._loadEachChildView (/data/data/org.nativescript.test/files/app/tns_modules/ui/core/view-common.js:739:18)
JS:     at Page.View.onLoaded (/data/data/org.nativescript.test/files/app/tns_modules/ui/core/view-common.js:729:14)
JS:     at Page.View.onLoaded (/data/data/org.nativescript.test/files/app/tns_modules/ui/core/view.js:82:35)
JS:     at Page.onLoaded (/data/data/org.nativescript.test/files/app/tns_modules/ui/page/page-common.js:53:35)
JS:     at eachChild (/data/data/org.nativescript.test/files/app/tns_modules/ui/core/view-common.js:736:23)
JS:     at ProxyViewContainer.LayoutBase._eachChildView (/data/data/org.nativescript.test/files/app/tns_modules/ui/layouts/layout-base-common.js:146:22)
JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
```

My setup is is exactly like in the example

**Comment by blaind** [comment]
Found a solution here: http://stackoverflow.com/a/38056722/499839
